### ISSUE TITLE
add systemd unit-file

### ISSUE THREAD

**Issue by TheAlgorythm** [DoorCam/DoorCam#8]

**Comment by TheAlgorythm** [comment]
It could need a working-dir for the templates
```toml
[Service]
Type=notify
WorkingDirectory=/sth
```
Some infos about systemd config can found here.
Implement with #6.
